// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJzadfhNLt2iqzeTuo9RzN0bJzjSAhuQ',
    appId: '1:1013722357225:web:2cfa4d2ff6dce08a07ff78',
    messagingSenderId: '1013722357225',
    projectId: 'deep-vid',
    authDomain: 'deep-vid.firebaseapp.com',
    storageBucket: 'deep-vid.firebasestorage.app',
    measurementId: 'G-M5Y7DLB16N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkclPimLAczAm5TDP94D_CTPY-svaZDmQ',
    appId: '1:1013722357225:android:5f23556a4d56a80207ff78',
    messagingSenderId: '1013722357225',
    projectId: 'deep-vid',
    storageBucket: 'deep-vid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5lDXRZALjghOCgj56SciH2RT6m5LDQA',
    appId: '1:1013722357225:ios:ce37f2e0ce214fea07ff78',
    messagingSenderId: '1013722357225',
    projectId: 'deep-vid',
    storageBucket: 'deep-vid.firebasestorage.app',
    iosBundleId: 'com.example.deepVid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5lDXRZALjghOCgj56SciH2RT6m5LDQA',
    appId: '1:1013722357225:ios:ce37f2e0ce214fea07ff78',
    messagingSenderId: '1013722357225',
    projectId: 'deep-vid',
    storageBucket: 'deep-vid.firebasestorage.app',
    iosBundleId: 'com.example.deepVid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJzadfhNLt2iqzeTuo9RzN0bJzjSAhuQ',
    appId: '1:1013722357225:web:622de6b3bdc364a507ff78',
    messagingSenderId: '1013722357225',
    projectId: 'deep-vid',
    authDomain: 'deep-vid.firebaseapp.com',
    storageBucket: 'deep-vid.firebasestorage.app',
    measurementId: 'G-0QQT6BM7ZK',
  );
}
